
package net.igorkromin.wsat.participant;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsAtExamplePortType", targetNamespace = "http://igorkromin.net/wsat/participant")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsAtExamplePortType {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "doOp", targetNamespace = "http://igorkromin.net/wsat/participant", className = "net.igorkromin.wsat.participant.DoOp")
    @ResponseWrapper(localName = "doOpResponse", targetNamespace = "http://igorkromin.net/wsat/participant", className = "net.igorkromin.wsat.participant.DoOpResponse")
    @Action(input = "http://igorkromin.net/wsat/participant/WsAtExamplePortType/doOpRequest", output = "http://igorkromin.net/wsat/participant/WsAtExamplePortType/doOpResponse")
    public void doOp();

}
