
package net.igorkromin.wsat.participant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsAtExampleService", targetNamespace = "http://igorkromin.net/wsat/participant", wsdlLocation = "http://127.0.0.1:7001/WsAtExample-1.0/WsAtExample?WSDL")
public class WsAtExampleService
    extends Service
{

    private final static URL WSATEXAMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSATEXAMPLESERVICE_EXCEPTION;
    private final static QName WSATEXAMPLESERVICE_QNAME = new QName("http://igorkromin.net/wsat/participant", "WsAtExampleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7001/WsAtExample-1.0/WsAtExample?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSATEXAMPLESERVICE_WSDL_LOCATION = url;
        WSATEXAMPLESERVICE_EXCEPTION = e;
    }

    public WsAtExampleService() {
        super(__getWsdlLocation(), WSATEXAMPLESERVICE_QNAME);
    }

    public WsAtExampleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSATEXAMPLESERVICE_QNAME, features);
    }

    public WsAtExampleService(URL wsdlLocation) {
        super(wsdlLocation, WSATEXAMPLESERVICE_QNAME);
    }

    public WsAtExampleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSATEXAMPLESERVICE_QNAME, features);
    }

    public WsAtExampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAtExampleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsAtExamplePortType
     */
    @WebEndpoint(name = "WsAtExamplePort")
    public WsAtExamplePortType getWsAtExamplePort() {
        return super.getPort(new QName("http://igorkromin.net/wsat/participant", "WsAtExamplePort"), WsAtExamplePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsAtExamplePortType
     */
    @WebEndpoint(name = "WsAtExamplePort")
    public WsAtExamplePortType getWsAtExamplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://igorkromin.net/wsat/participant", "WsAtExamplePort"), WsAtExamplePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSATEXAMPLESERVICE_EXCEPTION!= null) {
            throw WSATEXAMPLESERVICE_EXCEPTION;
        }
        return WSATEXAMPLESERVICE_WSDL_LOCATION;
    }

}
